name: Build and push Docker images
on: [push]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: eriksjolund/simd-diagonal-load-json-demo
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          dockerfile: Dockerfile.fedora
          add_git_labels: true

